sudo: required
language: node_js
branches:
  only:
    - master
    - next
cache:
  timeout: 600
  directories:
    - node_modules
    - apps/agent/node_modules
    - apps/finance/node_modules
    - apps/survey/node_modules
    - apps/token-manager/node_modules
    - apps/token-manager/app/node_modules
    - apps/vault/node_modules
    - apps/voting/node_modules
    - future-apps/payroll/node_modules
    - shared/migrations/node_modules
    - shared/minime/node_modules
    - shared/test-helpers/node_modules
notifications:
  email: false
node_js:
  - '8'
env:
  global:
    - INSTALL_FRONTEND=false
  matrix:
    - TASK=lint
    - TASK=test:agent
    - TASK=test:finance
    - TASK=test:survey
    - TASK=test:token-manager
    - TASK=test:token-manager:app INSTALL_FRONTEND=true
    - TASK=test:vault
    - TASK=test:voting
    - TASK=test:payroll
    - TASK=coverage:agent
    - TASK=coverage:finance
    - TASK=coverage:survey
    - TASK=coverage:token-manager
    - TASK=coverage:vault
    - TASK=coverage:voting
    - TASK=coverage:payroll
    - TASK=test:shared
matrix:
  allow_failures:
    - env: TASK=coverage:agent
    - env: TASK=coverage:payroll
install:
  - travis_wait 60 npm install
script:
  - travis_wait 60 npm run $TASK
after_success:
  - ./node_modules/.bin/lcov-result-merger 'apps/*/coverage/lcov.info' | ./node_modules/.bin/coveralls
